/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.sun.java.swing.plaf.windows.WindowsButtonUI;

/**
 *
 * @author Nas
 */
public class jfChapterOne extends javax.swing.JFrame {

    /**
     * Creates new form jfChapterOne
     */
    private boolean STATE;
    public jfChapterOne() {
        initComponents();
        setDesign();
        STATE = false;
    }

    private void setDesign(){
        btn_chap1_1.setUI(new WindowsButtonUI());
        btn_chap1_2.setUI(new WindowsButtonUI());
        btn_chap1_3.setUI(new WindowsButtonUI());
        btn_chap1_4.setUI(new WindowsButtonUI());
        btn_chap1_5.setUI(new WindowsButtonUI());
        btn_chap1_6.setUI(new WindowsButtonUI());
        btn_chap1_7.setUI(new WindowsButtonUI());
        btn_chap1_8.setUI(new WindowsButtonUI());
        btn_chap1_9.setUI(new WindowsButtonUI());
        
        pnlChap1_1.setVisible(STATE);
        setLocationRelativeTo(this);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_chap1_5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_chap1_9 = new javax.swing.JButton();
        btn_chap1_4 = new javax.swing.JButton();
        btn_chap1_2 = new javax.swing.JButton();
        btn_chap1_6 = new javax.swing.JButton();
        btn_chap1_8 = new javax.swing.JButton();
        btn_chap1_7 = new javax.swing.JButton();
        btn_chap1_1 = new javax.swing.JButton();
        btn_chap1_3 = new javax.swing.JButton();
        pnlChap1_1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        btn_chap1_5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_chap1_5.setText("   1.4: Scales of Measurement");
        btn_chap1_5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_chap1_5.setPreferredSize(new java.awt.Dimension(73, 35));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Module");
        setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Chapter 1: Introduction");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_chap1_9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_chap1_9.setText("   1.8: Summation Notation");
        btn_chap1_9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_chap1_9.setPreferredSize(new java.awt.Dimension(73, 35));

        btn_chap1_4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_chap1_4.setText("   1.4: Scales of Measurement");
        btn_chap1_4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_chap1_4.setPreferredSize(new java.awt.Dimension(73, 35));

        btn_chap1_2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_chap1_2.setText("   1.2: Role of Statistics");
        btn_chap1_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_chap1_2.setPreferredSize(new java.awt.Dimension(73, 35));

        btn_chap1_6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_chap1_6.setText("   1.5: Population and Samples");
        btn_chap1_6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_chap1_6.setPreferredSize(new java.awt.Dimension(73, 35));

        btn_chap1_8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_chap1_8.setText("   1.7: Descriptive Statistics and Inferential Statistics");
        btn_chap1_8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_chap1_8.setPreferredSize(new java.awt.Dimension(73, 35));

        btn_chap1_7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_chap1_7.setText("   1.6: Basic Sampling Techniques");
        btn_chap1_7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_chap1_7.setPreferredSize(new java.awt.Dimension(73, 35));

        btn_chap1_1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_chap1_1.setText("   1.1: Meaning of Statistics");
        btn_chap1_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_chap1_1.setPreferredSize(new java.awt.Dimension(73, 35));
        btn_chap1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chap1_1ActionPerformed(evt);
            }
        });

        btn_chap1_3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_chap1_3.setText("   1.3: Variables");
        btn_chap1_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_chap1_3.setPreferredSize(new java.awt.Dimension(73, 35));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_chap1_1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(btn_chap1_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_chap1_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_chap1_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_chap1_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_chap1_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_chap1_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_chap1_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_chap1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_chap1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_chap1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_chap1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_chap1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_chap1_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_chap1_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_chap1_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("          Statistics is a science that deals with techniques for collecting, analyzing, and drawing conclusions from data.\n          Statistics are numerical descriptions by which we enhance the understanding of data.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnlChap1_1Layout = new javax.swing.GroupLayout(pnlChap1_1);
        pnlChap1_1.setLayout(pnlChap1_1Layout);
        pnlChap1_1Layout.setHorizontalGroup(
            pnlChap1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChap1_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlChap1_1Layout.setVerticalGroup(
            pnlChap1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChap1_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlChap1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlChap1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chap1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chap1_1ActionPerformed
        // TODO add your handling code here:
        pnlChap1_1.setVisible(STATE? true: false);
        STATE = !STATE;
    }//GEN-LAST:event_btn_chap1_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfChapterOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfChapterOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfChapterOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfChapterOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfChapterOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chap1_1;
    private javax.swing.JButton btn_chap1_2;
    private javax.swing.JButton btn_chap1_3;
    private javax.swing.JButton btn_chap1_4;
    private javax.swing.JButton btn_chap1_5;
    private javax.swing.JButton btn_chap1_6;
    private javax.swing.JButton btn_chap1_7;
    private javax.swing.JButton btn_chap1_8;
    private javax.swing.JButton btn_chap1_9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnlChap1_1;
    // End of variables declaration//GEN-END:variables
}
